### Health check
GET http://localhost:3000/health HTTP/1.1
content-type: application/json

### GET All Users
GET http://localhost:3000/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTUzMzY4NjYsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTUzNDA0NjZ9.ggkqE-HeZkwBO5JDj9E2SkveSc-16_INgHV6Wryw7g0

### GET User by id
GET http://localhost:3000/v1/users/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTUzMzY4NjYsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTUzNDA0NjZ9.ggkqE-HeZkwBO5JDj9E2SkveSc-16_INgHV6Wryw7g0

### GET Publications
GET http://localhost:3000/v1/publications HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTUzMzY4NjYsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTUzNDA0NjZ9.ggkqE-HeZkwBO5JDj9E2SkveSc-16_INgHV6Wryw7g0

### GET Publication by id
GET http://localhost:3000/v1/publications/cme798has01mti07mvx3jtyod HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTUzMzY4NjYsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTUzNDA0NjZ9.ggkqE-HeZkwBO5JDj9E2SkveSc-16_INgHV6Wryw7g0

### GET Publication comments
GET http://localhost:3000/v1/publications/cme798has01mti07mvx3jtyod/comments HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTUzMzY4NjYsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTUzNDA0NjZ9.ggkqE-HeZkwBO5JDj9E2SkveSc-16_INgHV6Wryw7g0

### POST User
POST http://localhost:3000/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTUzMzY4NjYsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTUzNDA0NjZ9.ggkqE-HeZkwBO5JDj9E2SkveSc-16_INgHV6Wryw7g0

{ "username": "Validation User1231", "email": "v6M2F@example.com", "password": "123456", "fullname": "Validation", "birthdate": "2023-10-27T10:00:00Z", "avatar_url": "http://example.com/picture/check.webp"}

### PUT User
PUT http://localhost:3000/v1/users/cme9qjbrw0000i0dhbl852gg1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTUzMzY4NjYsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTUzNDA0NjZ9.ggkqE-HeZkwBO5JDj9E2SkveSc-16_INgHV6Wryw7g0

{ "avatar_url": "http://example.com/picture/zaebis.webp", "username": "lol kek"}

### DELETE User
DELETE http://localhost:3000/v1/users/cmee3355b0000i07owzd2pqly HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTUzMzY4NjYsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTUzNDA0NjZ9.ggkqE-HeZkwBO5JDj9E2SkveSc-16_INgHV6Wryw7g0
content-type: application/json

### POST Publication
POST http://localhost:3000/v1/publications HTTP/1.1
content-type: application/json

{"pictureUrl": "http://example.com/picture/check.webp", "userId": 1, "likes": 10, "description": "Hello world100500"}

### POST Comment
POST http://localhost:3000/v1/comments HTTP/1.1
content-type: application/json

{"userId": 1, "publicationId": 1, "message": "Very good picture"}