### Health check
GET http://localhost:3000/health HTTP/1.1
content-type: application/json

### GET All Users
GET http://localhost:3000/v1/users?limit=2&offset=0 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

### GET User by id
GET http://localhost:3000/v1/users/cme9qjbrw0000i0dhbl852gg1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

### GET Publications
GET http://localhost:3000/v1/publications?limit=2&offset=0 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

### GET Publication by id
GET http://localhost:3000/v1/publications/cmera1kg90003i0jfbb95of2y HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

### GET Publication comments
GET http://localhost:3000/v1/publications/cme9qjbto006yi0dhitxivxyd/comments HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

### POST User
POST http://localhost:3000/v1/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

{ "username": "CHECK USER PASSWORD", "email": "checkasDTO@check.com", "password": "2231", "fullname": "Validation", "birthdate": "2023-10-27T10:00:00Z", "avatar_url": "http://example.com/picture/check.webp"}

### PUT User
PUT http://localhost:3000/v1/users/cmesjw0b50000i0xz3z42yke2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

{ "avatar_url": "http://example.com/picture/zaebis.webp", "username": "lol666 k2ek"}

### POST Note
POST http://localhost:3000/v1/users/cme9qjc1201fri0dh5kzsrihj/note HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

{ "message": "ERR_VAL2223I2D", "auditory": "subscribed" }

### DELETE User
DELETE http://localhost:3000/v1/users/cmesl7mct0000i0affi6v5mhv HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q
content-type: application/json

### POST Publication
POST http://localhost:3000/v1/publications HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

{"picture_url": "http://example.com/picture/check.webp", "user_id": "cme9qjbrw0000i0dhbl852gg1","is_liked": false, "likes": 100500, "description": "Hello world100500"}

### PATCH Publication likes
PATCH  http://localhost:3000/v1/publications/cmer9ys5p0005i0f680otzqs7/like HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

### GET Comments
GET http://localhost:3000/v1/comments?limit=2&offset=0 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

### POST Comment
POST http://localhost:3000/v1/comments HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q

{"user_id": "cme9qjbrw0000i0dhbl852gg1", "publication_id": "cme9qjbv300fki0dho0ef8rho", "message": "Very good picture"}

### DELETE Comment
DELETE http://localhost:3000/v1/comments/cme9qjbs20004i0dhfsvqvsq7 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImNtZTlxamJydzAwMDBpMGRoYmw4NTJnZzEiLCJpYXQiOjE3NTYxMzQ0NTIsImlzcyI6InNlcnZlciIsImF1ZCI6InVzZXIiLCJleHAiOjE3NTY3MzkyNTJ9.E3QHxtJHiyXkbs9AXIHn0VXo186oRAWnG7CBv54K52Q
